/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PopularRouteImport } from './routes/popular'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as Jb12bzLoginRouteImport } from './routes/jb12bz-login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as Jb12bzRouteRouteImport } from './routes/jb12bz/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Jb12bzIndexRouteImport } from './routes/jb12bz/index'
import { Route as MealIdRouteImport } from './routes/meal.$id'
import { Route as Jb12bzUsersRouteImport } from './routes/jb12bz/users'
import { Route as Jb12bzSettingsRouteImport } from './routes/jb12bz/settings'
import { Route as Jb12bzRestaurantsRouteImport } from './routes/jb12bz/restaurants'
import { Route as Jb12bzMealsRouteImport } from './routes/jb12bz/meals'
import { Route as Jb12bzMealPlansRouteImport } from './routes/jb12bz/meal-plans'
import { Route as Jb12bzLeadsRouteImport } from './routes/jb12bz/leads'
import { Route as Jb12bzCitiesRouteImport } from './routes/jb12bz/cities'
import { Route as ApiPublicTmpResetRouteImport } from './routes/api/public/_tmp-reset'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PopularRoute = PopularRouteImport.update({
  id: '/popular',
  path: '/popular',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const Jb12bzLoginRoute = Jb12bzLoginRouteImport.update({
  id: '/jb12bz-login',
  path: '/jb12bz-login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const Jb12bzRouteRoute = Jb12bzRouteRouteImport.update({
  id: '/jb12bz',
  path: '/jb12bz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Jb12bzIndexRoute = Jb12bzIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Jb12bzRouteRoute,
} as any)
const MealIdRoute = MealIdRouteImport.update({
  id: '/meal/$id',
  path: '/meal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Jb12bzUsersRoute = Jb12bzUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => Jb12bzRouteRoute,
} as any)
const Jb12bzSettingsRoute = Jb12bzSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => Jb12bzRouteRoute,
} as any)
const Jb12bzRestaurantsRoute = Jb12bzRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => Jb12bzRouteRoute,
} as any)
const Jb12bzMealsRoute = Jb12bzMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => Jb12bzRouteRoute,
} as any)
const Jb12bzMealPlansRoute = Jb12bzMealPlansRouteImport.update({
  id: '/meal-plans',
  path: '/meal-plans',
  getParentRoute: () => Jb12bzRouteRoute,
} as any)
const Jb12bzLeadsRoute = Jb12bzLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => Jb12bzRouteRoute,
} as any)
const Jb12bzCitiesRoute = Jb12bzCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => Jb12bzRouteRoute,
} as any)
const ApiPublicTmpResetRoute = ApiPublicTmpResetRouteImport.update({
  id: '/api/public/_tmp-reset',
  path: '/api/public',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jb12bz': typeof Jb12bzRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/jb12bz-login': typeof Jb12bzLoginRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/popular': typeof PopularRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/today': typeof TodayRoute
  '/jb12bz/cities': typeof Jb12bzCitiesRoute
  '/jb12bz/leads': typeof Jb12bzLeadsRoute
  '/jb12bz/meal-plans': typeof Jb12bzMealPlansRoute
  '/jb12bz/meals': typeof Jb12bzMealsRoute
  '/jb12bz/restaurants': typeof Jb12bzRestaurantsRoute
  '/jb12bz/settings': typeof Jb12bzSettingsRoute
  '/jb12bz/users': typeof Jb12bzUsersRoute
  '/meal/$id': typeof MealIdRoute
  '/jb12bz/': typeof Jb12bzIndexRoute
  '/api/public': typeof ApiPublicTmpResetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/jb12bz-login': typeof Jb12bzLoginRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/popular': typeof PopularRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/today': typeof TodayRoute
  '/jb12bz/cities': typeof Jb12bzCitiesRoute
  '/jb12bz/leads': typeof Jb12bzLeadsRoute
  '/jb12bz/meal-plans': typeof Jb12bzMealPlansRoute
  '/jb12bz/meals': typeof Jb12bzMealsRoute
  '/jb12bz/restaurants': typeof Jb12bzRestaurantsRoute
  '/jb12bz/settings': typeof Jb12bzSettingsRoute
  '/jb12bz/users': typeof Jb12bzUsersRoute
  '/meal/$id': typeof MealIdRoute
  '/jb12bz': typeof Jb12bzIndexRoute
  '/api/public': typeof ApiPublicTmpResetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jb12bz': typeof Jb12bzRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/jb12bz-login': typeof Jb12bzLoginRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/popular': typeof PopularRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/today': typeof TodayRoute
  '/jb12bz/cities': typeof Jb12bzCitiesRoute
  '/jb12bz/leads': typeof Jb12bzLeadsRoute
  '/jb12bz/meal-plans': typeof Jb12bzMealPlansRoute
  '/jb12bz/meals': typeof Jb12bzMealsRoute
  '/jb12bz/restaurants': typeof Jb12bzRestaurantsRoute
  '/jb12bz/settings': typeof Jb12bzSettingsRoute
  '/jb12bz/users': typeof Jb12bzUsersRoute
  '/meal/$id': typeof MealIdRoute
  '/jb12bz/': typeof Jb12bzIndexRoute
  '/api/public/_tmp-reset': typeof ApiPublicTmpResetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/jb12bz'
    | '/auth'
    | '/change-password'
    | '/forgot-password'
    | '/home'
    | '/jb12bz-login'
    | '/onboarding'
    | '/planner'
    | '/popular'
    | '/profile'
    | '/reset-password'
    | '/restaurants'
    | '/saved'
    | '/settings'
    | '/shopping'
    | '/today'
    | '/jb12bz/cities'
    | '/jb12bz/leads'
    | '/jb12bz/meal-plans'
    | '/jb12bz/meals'
    | '/jb12bz/restaurants'
    | '/jb12bz/settings'
    | '/jb12bz/users'
    | '/meal/$id'
    | '/jb12bz/'
    | '/api/public'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/change-password'
    | '/forgot-password'
    | '/home'
    | '/jb12bz-login'
    | '/onboarding'
    | '/planner'
    | '/popular'
    | '/profile'
    | '/reset-password'
    | '/restaurants'
    | '/saved'
    | '/settings'
    | '/shopping'
    | '/today'
    | '/jb12bz/cities'
    | '/jb12bz/leads'
    | '/jb12bz/meal-plans'
    | '/jb12bz/meals'
    | '/jb12bz/restaurants'
    | '/jb12bz/settings'
    | '/jb12bz/users'
    | '/meal/$id'
    | '/jb12bz'
    | '/api/public'
  id:
    | '__root__'
    | '/'
    | '/jb12bz'
    | '/auth'
    | '/change-password'
    | '/forgot-password'
    | '/home'
    | '/jb12bz-login'
    | '/onboarding'
    | '/planner'
    | '/popular'
    | '/profile'
    | '/reset-password'
    | '/restaurants'
    | '/saved'
    | '/settings'
    | '/shopping'
    | '/today'
    | '/jb12bz/cities'
    | '/jb12bz/leads'
    | '/jb12bz/meal-plans'
    | '/jb12bz/meals'
    | '/jb12bz/restaurants'
    | '/jb12bz/settings'
    | '/jb12bz/users'
    | '/meal/$id'
    | '/jb12bz/'
    | '/api/public/_tmp-reset'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Jb12bzRouteRoute: typeof Jb12bzRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  Jb12bzLoginRoute: typeof Jb12bzLoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PlannerRoute: typeof PlannerRoute
  PopularRoute: typeof PopularRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RestaurantsRoute: typeof RestaurantsRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  ShoppingRoute: typeof ShoppingRoute
  TodayRoute: typeof TodayRoute
  MealIdRoute: typeof MealIdRoute
  ApiPublicTmpResetRoute: typeof ApiPublicTmpResetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popular': {
      id: '/popular'
      path: '/popular'
      fullPath: '/popular'
      preLoaderRoute: typeof PopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jb12bz-login': {
      id: '/jb12bz-login'
      path: '/jb12bz-login'
      fullPath: '/jb12bz-login'
      preLoaderRoute: typeof Jb12bzLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jb12bz': {
      id: '/jb12bz'
      path: '/jb12bz'
      fullPath: '/jb12bz'
      preLoaderRoute: typeof Jb12bzRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jb12bz/': {
      id: '/jb12bz/'
      path: '/'
      fullPath: '/jb12bz/'
      preLoaderRoute: typeof Jb12bzIndexRouteImport
      parentRoute: typeof Jb12bzRouteRoute
    }
    '/meal/$id': {
      id: '/meal/$id'
      path: '/meal/$id'
      fullPath: '/meal/$id'
      preLoaderRoute: typeof MealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jb12bz/users': {
      id: '/jb12bz/users'
      path: '/users'
      fullPath: '/jb12bz/users'
      preLoaderRoute: typeof Jb12bzUsersRouteImport
      parentRoute: typeof Jb12bzRouteRoute
    }
    '/jb12bz/settings': {
      id: '/jb12bz/settings'
      path: '/settings'
      fullPath: '/jb12bz/settings'
      preLoaderRoute: typeof Jb12bzSettingsRouteImport
      parentRoute: typeof Jb12bzRouteRoute
    }
    '/jb12bz/restaurants': {
      id: '/jb12bz/restaurants'
      path: '/restaurants'
      fullPath: '/jb12bz/restaurants'
      preLoaderRoute: typeof Jb12bzRestaurantsRouteImport
      parentRoute: typeof Jb12bzRouteRoute
    }
    '/jb12bz/meals': {
      id: '/jb12bz/meals'
      path: '/meals'
      fullPath: '/jb12bz/meals'
      preLoaderRoute: typeof Jb12bzMealsRouteImport
      parentRoute: typeof Jb12bzRouteRoute
    }
    '/jb12bz/meal-plans': {
      id: '/jb12bz/meal-plans'
      path: '/meal-plans'
      fullPath: '/jb12bz/meal-plans'
      preLoaderRoute: typeof Jb12bzMealPlansRouteImport
      parentRoute: typeof Jb12bzRouteRoute
    }
    '/jb12bz/leads': {
      id: '/jb12bz/leads'
      path: '/leads'
      fullPath: '/jb12bz/leads'
      preLoaderRoute: typeof Jb12bzLeadsRouteImport
      parentRoute: typeof Jb12bzRouteRoute
    }
    '/jb12bz/cities': {
      id: '/jb12bz/cities'
      path: '/cities'
      fullPath: '/jb12bz/cities'
      preLoaderRoute: typeof Jb12bzCitiesRouteImport
      parentRoute: typeof Jb12bzRouteRoute
    }
    '/api/public/_tmp-reset': {
      id: '/api/public/_tmp-reset'
      path: '/api/public'
      fullPath: '/api/public'
      preLoaderRoute: typeof ApiPublicTmpResetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Jb12bzRouteRouteChildren {
  Jb12bzCitiesRoute: typeof Jb12bzCitiesRoute
  Jb12bzLeadsRoute: typeof Jb12bzLeadsRoute
  Jb12bzMealPlansRoute: typeof Jb12bzMealPlansRoute
  Jb12bzMealsRoute: typeof Jb12bzMealsRoute
  Jb12bzRestaurantsRoute: typeof Jb12bzRestaurantsRoute
  Jb12bzSettingsRoute: typeof Jb12bzSettingsRoute
  Jb12bzUsersRoute: typeof Jb12bzUsersRoute
  Jb12bzIndexRoute: typeof Jb12bzIndexRoute
}

const Jb12bzRouteRouteChildren: Jb12bzRouteRouteChildren = {
  Jb12bzCitiesRoute: Jb12bzCitiesRoute,
  Jb12bzLeadsRoute: Jb12bzLeadsRoute,
  Jb12bzMealPlansRoute: Jb12bzMealPlansRoute,
  Jb12bzMealsRoute: Jb12bzMealsRoute,
  Jb12bzRestaurantsRoute: Jb12bzRestaurantsRoute,
  Jb12bzSettingsRoute: Jb12bzSettingsRoute,
  Jb12bzUsersRoute: Jb12bzUsersRoute,
  Jb12bzIndexRoute: Jb12bzIndexRoute,
}

const Jb12bzRouteRouteWithChildren = Jb12bzRouteRoute._addFileChildren(
  Jb12bzRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Jb12bzRouteRoute: Jb12bzRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  Jb12bzLoginRoute: Jb12bzLoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlannerRoute: PlannerRoute,
  PopularRoute: PopularRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RestaurantsRoute: RestaurantsRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  ShoppingRoute: ShoppingRoute,
  TodayRoute: TodayRoute,
  MealIdRoute: MealIdRoute,
  ApiPublicTmpResetRoute: ApiPublicTmpResetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
