/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PopularRouteImport } from './routes/popular'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as Jb12bzLoginRouteImport } from './routes/jb12bz-login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as MealIdRouteImport } from './routes/meal.$id'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRestaurantsRouteImport } from './routes/admin/restaurants'
import { Route as AdminNutritionRouteImport } from './routes/admin/nutrition'
import { Route as AdminMealsRouteImport } from './routes/admin/meals'
import { Route as AdminMealPlansRouteImport } from './routes/admin/meal-plans'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminIngredientsRouteImport } from './routes/admin/ingredients'
import { Route as AdminCitiesRouteImport } from './routes/admin/cities'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PopularRoute = PopularRouteImport.update({
  id: '/popular',
  path: '/popular',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const Jb12bzLoginRoute = Jb12bzLoginRouteImport.update({
  id: '/jb12bz-login',
  path: '/jb12bz-login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const MealIdRoute = MealIdRouteImport.update({
  id: '/meal/$id',
  path: '/meal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRestaurantsRoute = AdminRestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNutritionRoute = AdminNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMealsRoute = AdminMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMealPlansRoute = AdminMealPlansRouteImport.update({
  id: '/meal-plans',
  path: '/meal-plans',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIngredientsRoute = AdminIngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCitiesRoute = AdminCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/jb12bz-login': typeof Jb12bzLoginRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/popular': typeof PopularRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/today': typeof TodayRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/ingredients': typeof AdminIngredientsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/meal-plans': typeof AdminMealPlansRoute
  '/admin/meals': typeof AdminMealsRoute
  '/admin/nutrition': typeof AdminNutritionRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/meal/$id': typeof MealIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/jb12bz-login': typeof Jb12bzLoginRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/popular': typeof PopularRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/today': typeof TodayRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/ingredients': typeof AdminIngredientsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/meal-plans': typeof AdminMealPlansRoute
  '/admin/meals': typeof AdminMealsRoute
  '/admin/nutrition': typeof AdminNutritionRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/meal/$id': typeof MealIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/jb12bz-login': typeof Jb12bzLoginRoute
  '/onboarding': typeof OnboardingRoute
  '/planner': typeof PlannerRoute
  '/popular': typeof PopularRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/restaurants': typeof RestaurantsRoute
  '/saved': typeof SavedRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
  '/today': typeof TodayRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/ingredients': typeof AdminIngredientsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/meal-plans': typeof AdminMealPlansRoute
  '/admin/meals': typeof AdminMealsRoute
  '/admin/nutrition': typeof AdminNutritionRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/meal/$id': typeof MealIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/change-password'
    | '/forgot-password'
    | '/home'
    | '/jb12bz-login'
    | '/onboarding'
    | '/planner'
    | '/popular'
    | '/profile'
    | '/reset-password'
    | '/restaurants'
    | '/saved'
    | '/settings'
    | '/shopping'
    | '/today'
    | '/admin/categories'
    | '/admin/cities'
    | '/admin/ingredients'
    | '/admin/leads'
    | '/admin/meal-plans'
    | '/admin/meals'
    | '/admin/nutrition'
    | '/admin/restaurants'
    | '/admin/settings'
    | '/admin/users'
    | '/meal/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/change-password'
    | '/forgot-password'
    | '/home'
    | '/jb12bz-login'
    | '/onboarding'
    | '/planner'
    | '/popular'
    | '/profile'
    | '/reset-password'
    | '/restaurants'
    | '/saved'
    | '/settings'
    | '/shopping'
    | '/today'
    | '/admin/categories'
    | '/admin/cities'
    | '/admin/ingredients'
    | '/admin/leads'
    | '/admin/meal-plans'
    | '/admin/meals'
    | '/admin/nutrition'
    | '/admin/restaurants'
    | '/admin/settings'
    | '/admin/users'
    | '/meal/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/change-password'
    | '/forgot-password'
    | '/home'
    | '/jb12bz-login'
    | '/onboarding'
    | '/planner'
    | '/popular'
    | '/profile'
    | '/reset-password'
    | '/restaurants'
    | '/saved'
    | '/settings'
    | '/shopping'
    | '/today'
    | '/admin/categories'
    | '/admin/cities'
    | '/admin/ingredients'
    | '/admin/leads'
    | '/admin/meal-plans'
    | '/admin/meals'
    | '/admin/nutrition'
    | '/admin/restaurants'
    | '/admin/settings'
    | '/admin/users'
    | '/meal/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  Jb12bzLoginRoute: typeof Jb12bzLoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PlannerRoute: typeof PlannerRoute
  PopularRoute: typeof PopularRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RestaurantsRoute: typeof RestaurantsRoute
  SavedRoute: typeof SavedRoute
  SettingsRoute: typeof SettingsRoute
  ShoppingRoute: typeof ShoppingRoute
  TodayRoute: typeof TodayRoute
  MealIdRoute: typeof MealIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popular': {
      id: '/popular'
      path: '/popular'
      fullPath: '/popular'
      preLoaderRoute: typeof PopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jb12bz-login': {
      id: '/jb12bz-login'
      path: '/jb12bz-login'
      fullPath: '/jb12bz-login'
      preLoaderRoute: typeof Jb12bzLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/meal/$id': {
      id: '/meal/$id'
      path: '/meal/$id'
      fullPath: '/meal/$id'
      preLoaderRoute: typeof MealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/restaurants': {
      id: '/admin/restaurants'
      path: '/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AdminRestaurantsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/nutrition': {
      id: '/admin/nutrition'
      path: '/nutrition'
      fullPath: '/admin/nutrition'
      preLoaderRoute: typeof AdminNutritionRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/meals': {
      id: '/admin/meals'
      path: '/meals'
      fullPath: '/admin/meals'
      preLoaderRoute: typeof AdminMealsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/meal-plans': {
      id: '/admin/meal-plans'
      path: '/meal-plans'
      fullPath: '/admin/meal-plans'
      preLoaderRoute: typeof AdminMealPlansRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ingredients': {
      id: '/admin/ingredients'
      path: '/ingredients'
      fullPath: '/admin/ingredients'
      preLoaderRoute: typeof AdminIngredientsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/cities': {
      id: '/admin/cities'
      path: '/cities'
      fullPath: '/admin/cities'
      preLoaderRoute: typeof AdminCitiesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCitiesRoute: typeof AdminCitiesRoute
  AdminIngredientsRoute: typeof AdminIngredientsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminMealPlansRoute: typeof AdminMealPlansRoute
  AdminMealsRoute: typeof AdminMealsRoute
  AdminNutritionRoute: typeof AdminNutritionRoute
  AdminRestaurantsRoute: typeof AdminRestaurantsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCitiesRoute: AdminCitiesRoute,
  AdminIngredientsRoute: AdminIngredientsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminMealPlansRoute: AdminMealPlansRoute,
  AdminMealsRoute: AdminMealsRoute,
  AdminNutritionRoute: AdminNutritionRoute,
  AdminRestaurantsRoute: AdminRestaurantsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  Jb12bzLoginRoute: Jb12bzLoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlannerRoute: PlannerRoute,
  PopularRoute: PopularRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RestaurantsRoute: RestaurantsRoute,
  SavedRoute: SavedRoute,
  SettingsRoute: SettingsRoute,
  ShoppingRoute: ShoppingRoute,
  TodayRoute: TodayRoute,
  MealIdRoute: MealIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
