BEGIN;

-- Replace the old generated restaurant list with the verified workbook branches.
DELETE FROM public.restaurants;

WITH food_rows(category_slug, name, slug, aliases) AS (
  VALUES
  ('beans', 'Moi Moi', 'beans-moi-moi', ARRAY['Moin Moin']::text[]),
  ('beans', 'Plain Beans', 'beans-plain-beans', ARRAY['Plain Beans']::text[]),
  ('beans', 'Ewa Agoyin', 'beans-ewa-agoyin', ARRAY['Ewa Agoyin']::text[]),
  ('beans', 'Porridge Beans', 'beans-porridge-beans', ARRAY['Porridge Beans']::text[]),
  ('other', 'African', 'other-african', ARRAY['African']::text[]),
  ('other', 'Bakery', 'other-bakery', ARRAY['Bakery']::text[]),
  ('other', 'Breakfast', 'other-breakfast', ARRAY['Breakfast']::text[]),
  ('other', 'Burger', 'other-burger', ARRAY['Burger']::text[]),
  ('other', 'Burgers', 'other-burgers', ARRAY['Burgers']::text[]),
  ('other', 'Chicken Pie', 'other-chicken-pie', ARRAY['Chicken Pie']::text[]),
  ('other', 'Chinese', 'other-chinese', ARRAY['Chinese']::text[]),
  ('other', 'Continental', 'other-continental', ARRAY['Continental']::text[]),
  ('other', 'Fast Food', 'other-fast-food', ARRAY['Fast Food']::text[]),
  ('other', 'Intercontinental', 'other-intercontinental', ARRAY['Intercontinental']::text[]),
  ('other', 'Juice', 'other-juice', ARRAY['Juice']::text[]),
  ('other', 'Local Dishes', 'other-local-dishes', ARRAY['Local Dishes','local food','naija food','nigerian food']::text[]),
  ('other', 'Meat Pie', 'other-meat-pie', ARRAY['Meat Pie']::text[]),
  ('other', 'Nigerian Food', 'other-nigerian-food', ARRAY['Nigerian Food']::text[]),
  ('other', 'Nkwobi', 'other-nkwobi', ARRAY['Nkwobi']::text[]),
  ('other', 'Parfait', 'other-parfait', ARRAY['Parfait']::text[]),
  ('other', 'Pasta', 'other-pasta', ARRAY['noodles','Pasta','spaghetti','spaghetti and vegetables','spaghetti with vegetables']::text[]),
  ('other', 'Pastries', 'other-pastries', ARRAY['Pastries']::text[]),
  ('other', 'Pizza', 'other-pizza', ARRAY['Pizza']::text[]),
  ('other', 'Salad', 'other-salad', ARRAY['Salad','Salads']::text[]),
  ('other', 'Sandwich', 'other-sandwich', ARRAY['Sandwich']::text[]),
  ('other', 'Shawarma', 'other-shawarma', ARRAY['Shawarma']::text[]),
  ('other', 'Snack Bar', 'other-snack-bar', ARRAY['Snack Bar']::text[]),
  ('other', 'Soft Drinks', 'other-soft-drinks', ARRAY['Soft Drinks']::text[]),
  ('other', 'Sides', 'other-sides', ARRAY['Sides']::text[]),
  ('other', 'Tigernut Milk', 'other-tigernut-milk', ARRAY['Tigernut Milk']::text[]),
  ('other', 'Warm Food', 'other-warm-food', ARRAY['Warm Food']::text[]),
  ('other', 'Wellness Juice', 'other-wellness-juice', ARRAY['Wellness Juice']::text[]),
  ('other', 'Wraps', 'other-wraps', ARRAY['Wraps']::text[]),
  ('other', 'Yoghurt', 'other-yoghurt', ARRAY['Yoghurt','Yoghurt Smoothie']::text[]),
  ('plantain', 'Fried Plantain', 'plantain-fried-plantain', ARRAY['Fried Plantain','dodo']::text[]),
  ('plantain', 'Kelewele', 'plantain-kelewele', ARRAY['Kelewele']::text[]),
  ('plantain', 'Plantain', 'plantain-plantain', ARRAY['Plantain']::text[]),
  ('protein', 'Chicken', 'protein-chicken', ARRAY['Chicken','fried chicken','grilled chicken']::text[]),
  ('protein', 'Grills', 'protein-grills', ARRAY['grill','Grills','grilled chicken']::text[]),
  ('protein', 'Seafood', 'protein-seafood', ARRAY['Seafood']::text[]),
  ('protein', 'Suya', 'protein-suya', ARRAY['Suya']::text[]),
  ('rice', 'Basmati Rice', 'rice-basmati-rice', ARRAY['Basmati Rice']::text[]),
  ('rice', 'Chinese Fried Rice', 'rice-chinese-fried-rice', ARRAY['Chinese Fried Rice']::text[]),
  ('rice', 'Coconut Rice', 'rice-coconut-rice', ARRAY['Coconut Rice']::text[]),
  ('rice', 'Fried Rice', 'rice-fried-rice', ARRAY['Fried Rice']::text[]),
  ('rice', 'Jollof Rice', 'rice-jollof-rice', ARRAY['jollof','jollof rice','Jollof Rice']::text[]),
  ('rice', 'Local Rice', 'rice-local-rice', ARRAY['Local Rice']::text[]),
  ('rice', 'Mega Rice', 'rice-mega-rice', ARRAY['Mega Rice']::text[]),
  ('rice', 'Ofada Rice', 'rice-ofada-rice', ARRAY['Ofada Rice']::text[]),
  ('rice', 'Ram Suya Rice', 'rice-ram-suya-rice', ARRAY['Ram Suya Rice']::text[]),
  ('rice', 'Rice', 'rice-rice', ARRAY['Rice','rice']::text[]),
  ('rice', 'Rice And Beans', 'rice-rice-and-beans', ARRAY['Rice and Beans']::text[]),
  ('rice', 'Rice And Gravy', 'rice-rice-and-gravy', ARRAY['Rice & Gravy']::text[]),
  ('rice', 'Special Rice Combo', 'rice-special-rice-combo', ARRAY['Special Rice Combo']::text[]),
  ('rice', 'White Rice', 'rice-white-rice', ARRAY['White Rice']::text[]),
  ('soup', 'Afang Soup', 'soup-afang-soup', ARRAY['Afang Soup']::text[]),
  ('soup', 'Banga Soup', 'soup-banga-soup', ARRAY['Banga Soup']::text[]),
  ('soup', 'Bitterleaf Soup', 'soup-bitterleaf-soup', ARRAY['Bitterleaf Soup']::text[]),
  ('soup', 'Edikang Ikong Soup', 'soup-edikang-ikong-soup', ARRAY['Edikang Ikong Soup']::text[]),
  ('soup', 'Efo Riro', 'soup-efo-riro', ARRAY['Efo Riro']::text[]),
  ('soup', 'Egusi Soup', 'soup-egusi-soup', ARRAY['Egusi','Egusi Soup']::text[]),
  ('soup', 'Ewedu', 'soup-ewedu', ARRAY['Ewedu']::text[]),
  ('soup', 'Gbegiri', 'soup-gbegiri', ARRAY['Gbegiri']::text[]),
  ('soup', 'Ofe Owerri', 'soup-ofe-owerri', ARRAY['Ofe Owerri']::text[]),
  ('soup', 'Ogbono Soup', 'soup-ogbono-soup', ARRAY['Ogbono Soup']::text[]),
  ('soup', 'Oha Soup', 'soup-oha-soup', ARRAY['Oha Soup']::text[]),
  ('soup', 'Okra Soup', 'soup-okra-soup', ARRAY['Okro Soup']::text[]),
  ('soup', 'Pepper Soup', 'soup-pepper-soup', ARRAY['Pepper Soup']::text[]),
  ('soup', 'Seafood Okra Soup', 'soup-seafood-okra-soup', ARRAY['Seafood Okra']::text[]),
  ('soup', 'Soup', 'soup-soup', ARRAY['Soup']::text[]),
  ('swallow', 'Amala', 'swallow-amala', ARRAY['Amala']::text[]),
  ('swallow', 'Pounded Yam', 'swallow-pounded-yam', ARRAY['Pounded Yam']::text[]),
  ('swallow', 'Semovita', 'swallow-semovita', ARRAY['Semovita']::text[]),
  ('swallow', 'Swallow', 'swallow-swallow', ARRAY['Swallow']::text[]),
  ('swallow', 'Wheat Swallow', 'swallow-wheat-swallow', ARRAY['Wheat']::text[]),
  ('yam', 'French Fries', 'yam-french-fries', ARRAY['French Fries']::text[]),
  ('yam', 'Fried Yam', 'yam-fried-yam', ARRAY['Fried Yam']::text[]),
  ('yam', 'Yam', 'yam-yam', ARRAY['Yam']::text[]),
  ('yam', 'Yam Chips', 'yam-yam-chips', ARRAY['Yam Chips']::text[])
), prepared_foods AS (
  SELECT category_slug, name, slug, array_agg(DISTINCT alias ORDER BY alias) AS aliases
  FROM food_rows, unnest(aliases) AS alias
  GROUP BY category_slug, name, slug
)
INSERT INTO public.foods (slug, name, category_id, aliases)
SELECT pf.slug, pf.name, fc.id, pf.aliases
FROM prepared_foods pf
LEFT JOIN public.food_categories fc ON fc.slug = pf.category_slug
ON CONFLICT (slug) DO UPDATE
SET aliases = (
  SELECT array_agg(DISTINCT alias ORDER BY alias)
  FROM unnest(public.foods.aliases || excluded.aliases) AS alias
), updated_at = now();

INSERT INTO public.restaurants (
  slug, name, chain, branch_name, city, area, state, address, phone,
  latitude, longitude, google_maps_url, source_url, verification_status, tags,
  rating, distance_km, delivery, verified, status, has_verified_food_data,
  restaurant_data_source, food_data_priority, last_imported_at, needs_review, cover_url
)
VALUES
  ('blackbell-restaurant-lekki-phase-1-lagos', 'Blackbell Restaurant — Lekki Phase 1', 'Blackbell Restaurant', 'Lekki Phase 1', 'Lagos', 'Lekki Phase 1', 'Lagos', 'Plot 18, Block 130, Admiralty Way, Lekki Phase 1, Lagos', '+234 818 200 6666', 6.4481, 3.4812, 'https://maps.google.com/?q=Blackbell+Admiralty+Way+Lekki', NULL, 'Existing workbook record', ARRAY['Continental','Intercontinental','Local Dishes']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('bukka-hut-ajao-estate-lagos', 'Bukka Hut — Ajao Estate', 'Bukka Hut', 'Ajao Estate', 'Lagos', 'Ajao Estate', 'Lagos', '8A Osolo Way, By 7/8 Bus Stop, Ajao Estate, Lagos', '+234 700 055 0055', NULL, NULL, NULL, 'https://bukkahut.com/our-menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Soup','Yam','Nigerian Food','Suya','Grills','Shawarma','Nkwobi']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('bukka-hut-chevron-lagos', 'Bukka Hut — Chevron', 'Bukka Hut', 'Chevron', 'Lagos', 'Chevron', 'Lagos', 'Chevron Drive, Lekki Peninsula, Lagos', '+234 700 055 0055', NULL, NULL, NULL, 'https://bukkahut.com/our-menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Soup','Yam','Nigerian Food','Suya','Grills','Shawarma','Nkwobi']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('bukka-hut-festac-lagos', 'Bukka Hut — Festac', 'Bukka Hut', 'Festac', 'Lagos', 'Festac', 'Lagos', 'Festival Mall, Amuwo Odofin Estate, Lagos', '+234 700 055 0055', NULL, NULL, NULL, 'https://bukkahut.com/our-menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Soup','Yam','Nigerian Food','Suya','Grills','Shawarma','Nkwobi']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('bukka-hut-gbagada-lagos', 'Bukka Hut — Gbagada', 'Bukka Hut', 'Gbagada', 'Lagos', 'Gbagada', 'Lagos', 'Plot 278, Gbagada-Oworonshoki Expressway, Gbagada, Lagos', '+234 700 055 0055', NULL, NULL, NULL, 'https://bukkahut.com/our-menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Soup','Yam','Nigerian Food','Suya','Grills','Shawarma','Nkwobi']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('bukka-hut-ikota-lagos', 'Bukka Hut — Ikota', 'Bukka Hut', 'Ikota', 'Lagos', 'Ikota', 'Lagos', 'Ikota Shopping Complex, Lekki, Lagos', '+234 700 055 0055', NULL, NULL, NULL, 'https://bukkahut.com/our-menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Soup','Yam','Nigerian Food','Suya','Grills','Shawarma','Nkwobi']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('bukka-hut-ikeja-gra-lagos', 'Bukka Hut — Ikeja GRA', 'Bukka Hut', 'Ikeja GRA', 'Lagos', 'Ikeja GRA', 'Lagos', '16 Oduduwa Way, Ikeja GRA, Lagos', '+234 700 055 0055', NULL, NULL, NULL, 'https://bukkahut.com/our-menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Soup','Yam','Nigerian Food','Suya','Grills','Shawarma','Nkwobi']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('bukka-hut-ikotun-lagos', 'Bukka Hut — Ikotun', 'Bukka Hut', 'Ikotun', 'Lagos', 'Ikotun', 'Lagos', 'Ikotun-Egbe Road, Ikotun, Lagos', '+234 700 055 0055', NULL, NULL, NULL, 'https://bukkahut.com/our-menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Soup','Yam','Nigerian Food','Suya','Grills','Shawarma','Nkwobi']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('bukka-hut-ilupeju-lagos', 'Bukka Hut — Ilupeju', 'Bukka Hut', 'Ilupeju', 'Lagos', 'Ilupeju', 'Lagos', 'Commercial Avenue, Ilupeju, Lagos', '+234 700 055 0055', NULL, NULL, NULL, 'https://bukkahut.com/our-menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Soup','Yam','Nigerian Food','Suya','Grills','Shawarma','Nkwobi']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('bukka-hut-lekki-phase-1-lagos', 'Bukka Hut — Lekki Phase 1', 'Bukka Hut', 'Lekki Phase 1', 'Lagos', 'Lekki Phase 1', 'Lagos', 'Admiralty Road, Lekki Phase 1, Lagos', '+234 700 055 0055', NULL, NULL, NULL, 'https://bukkahut.com/our-menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Soup','Yam','Nigerian Food','Suya','Grills','Shawarma','Nkwobi']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('bukka-hut-mma2-airport-lagos', 'Bukka Hut — MMA2 Airport', 'Bukka Hut', 'MMA2 Airport', 'Lagos', 'Ikeja', 'Lagos', 'Terminal 2, Murtala Muhammed Airport, Ikeja, Lagos', '+234 700 055 0055', NULL, NULL, NULL, 'https://bukkahut.com/our-menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Soup','Yam','Nigerian Food','Suya','Grills','Shawarma','Nkwobi']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('bukka-hut-ogba-lagos', 'Bukka Hut — Ogba', 'Bukka Hut', 'Ogba', 'Lagos', 'Ogba', 'Lagos', 'Ogba, Lagos', '+234 700 055 0055', NULL, NULL, NULL, 'https://bukkahut.com/our-menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Soup','Yam','Nigerian Food','Suya','Grills','Shawarma','Nkwobi']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('bukka-hut-sangotedo-lagos', 'Bukka Hut — Sangotedo', 'Bukka Hut', 'Sangotedo', 'Lagos', 'Sangotedo', 'Lagos', 'Novare Mall, Sangotedo, Lagos', '+234 700 055 0055', NULL, NULL, NULL, 'https://bukkahut.com/our-menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Soup','Yam','Nigerian Food','Suya','Grills','Shawarma','Nkwobi']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('bukka-hut-surulere-lagos', 'Bukka Hut — Surulere', 'Bukka Hut', 'Surulere', 'Lagos', 'Surulere', 'Lagos', 'Adeniran Ogunsanya Street, Surulere, Lagos', '+234 700 055 0055', NULL, NULL, NULL, 'https://bukkahut.com/our-menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Soup','Yam','Nigerian Food','Suya','Grills','Shawarma','Nkwobi']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('bukka-hut-yaba-lagos', 'Bukka Hut — Yaba', 'Bukka Hut', 'Yaba', 'Lagos', 'Yaba', 'Lagos', 'Yaba, Lagos', '+234 700 055 0055', NULL, NULL, NULL, 'https://bukkahut.com/our-menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Soup','Yam','Nigerian Food','Suya','Grills','Shawarma','Nkwobi']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('chicken-republic-berger-lagos', 'Chicken Republic — Berger', 'Chicken Republic', 'Berger', 'Lagos', 'Berger', 'Lagos', 'Berger, Lagos', '+234 809 016 5440', NULL, NULL, NULL, NULL, 'Location supplied in chat; food data verified from official chain menu', ARRAY['Fast Food','Chicken','Bread','Shawarma','Soft Drinks','Burger']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('chicken-republic-festac-lagos', 'Chicken Republic — Festac', 'Chicken Republic', 'Festac', 'Lagos', 'Festac', 'Lagos', 'Festac Town, Lagos State', '+234 809 016 5441', NULL, NULL, NULL, NULL, 'Location supplied in chat; food data verified from official chain menu', ARRAY['Fast Food','Chicken','Bread','Shawarma','Soft Drinks','Burger']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('chicken-republic-garki-abuja', 'Chicken Republic — Garki', 'Chicken Republic', 'Garki', 'Abuja', 'Garki', 'Abuja', 'Area 11, Corner Shops, Garki, Abuja', '+234 809 016 5445', 9.0345, 7.489, 'https://maps.google.com/?q=Chicken+Republic+Garki+Abuja', NULL, 'Existing workbook record', ARRAY['Fast Food','Chicken']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('chicken-republic-ikeja-gra-lagos', 'Chicken Republic — Ikeja GRA', 'Chicken Republic', 'Ikeja GRA', 'Lagos', 'Ikeja GRA', 'Lagos', '53 Isaac John Street, Adebol Shopping Mall, Ikeja, Lagos State', '+234 809 016 5447', NULL, NULL, NULL, NULL, 'Location supplied in chat; food data verified from official chain menu', ARRAY['Fast Food','Chicken','Bread','Shawarma','Soft Drinks','Burger']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('chicken-republic-ikotun-lagos', 'Chicken Republic — Ikotun', 'Chicken Republic', 'Ikotun', 'Lagos', 'Ikotun', 'Lagos', 'Ikotun, Lagos State', '+234 809 016 5442', NULL, NULL, NULL, NULL, 'Location supplied in chat; food data verified from official chain menu', ARRAY['Fast Food','Chicken','Bread','Shawarma','Soft Drinks','Burger']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('chicken-republic-maryland-lagos', 'Chicken Republic — Maryland', 'Chicken Republic', 'Maryland', 'Lagos', 'Maryland', 'Lagos', 'Maryland Mall, Ikorodu Road, Maryland, Lagos State', '+234 809 016 5443', NULL, NULL, NULL, NULL, 'Location supplied in chat; food data verified from official chain menu', ARRAY['Fast Food','Chicken','Bread','Shawarma','Soft Drinks','Burger']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('chicken-republic-opebi-lagos', 'Chicken Republic — Opebi', 'Chicken Republic', 'Opebi', 'Lagos', 'Opebi', 'Lagos', '37A Opebi Road, Ikeja, Lagos State', '+234 809 016 5450', NULL, NULL, NULL, NULL, 'Location supplied in chat; food data verified from official chain menu', ARRAY['Fast Food','Chicken','Meat Pie']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('chicken-republic-sangotedo-lagos', 'Chicken Republic — Sangotedo', 'Chicken Republic', 'Sangotedo', 'Lagos', 'Sangotedo', 'Lagos', 'Sangotedo, Lagos State', '+234 809 016 5446', NULL, NULL, NULL, NULL, 'Location supplied in chat; food data verified from official chain menu', ARRAY['Fast Food','Chicken','Bread','Shawarma','Soft Drinks','Burger']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('chicken-republic-surulere-lagos', 'Chicken Republic — Surulere', 'Chicken Republic', 'Surulere', 'Lagos', 'Surulere', 'Lagos', 'Surulere, Lagos State', '+234 809 016 5448', NULL, NULL, NULL, NULL, 'Location supplied in chat; food data verified from official chain menu', ARRAY['Fast Food','Chicken','Bread','Shawarma','Soft Drinks','Burger']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('chicken-republic-wuse-ii-abuja', 'Chicken Republic — Wuse II', 'Chicken Republic', 'Wuse II', 'Abuja', 'Wuse II', 'Abuja', 'Plot 1251, Aminu Kano Crescent, Wuse II, Abuja', '+234 809 016 5444', 9.0765, 7.4761, 'https://maps.google.com/?q=Chicken+Republic+Aminu+Kano+Abuja', NULL, 'Existing workbook record', ARRAY['Fast Food','Chicken','Sides']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('fruity-life-ikeja-lagos', 'Fruity Life — Ikeja', 'Fruity Life', 'Ikeja', 'Lagos', 'Ikeja', 'Lagos', 'Ikeja City Mall, Ikeja, Lagos', '+234 913 000 4000', NULL, NULL, NULL, 'https://www.fruitylife.com.ng/menu', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Parfait','Yoghurt','Sandwich','Wraps','Warm Food','Tigernut Milk','Snack Bar','Salad','Yoghurt Smoothie','Juice','Wellness Juice']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('item-7-berger-lagos', 'Item 7 — Berger', 'Item 7', 'Berger', 'Lagos', 'Berger', 'Lagos', 'Berger, Lagos', '+234 814 000 7010', NULL, NULL, NULL, 'https://item7deals.com/menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Shawarma','Burger','Pasta','Snacks']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('item-7-ibadan-ibadan', 'Item 7 — Ibadan', 'Item 7', 'Ibadan', 'Ibadan', 'Ibadan', 'Oyo', 'Ibadan, Oyo State', '+234 814 000 7030', NULL, NULL, NULL, 'https://item7deals.com/menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Shawarma','Burger','Pasta','Snacks']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('item-7-ikota-lagos', 'Item 7 — Ikota', 'Item 7', 'Ikota', 'Lagos', 'Ikota', 'Lagos', 'Ikota, Lagos', '+234 814 000 7011', NULL, NULL, NULL, 'https://item7deals.com/menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Shawarma','Burger','Pasta','Snacks']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('item-7-lekki-lagos', 'Item 7 — Lekki', 'Item 7', 'Lekki', 'Lagos', 'Lekki', 'Lagos', 'Lekki, Lagos', '+234 814 000 7012', NULL, NULL, NULL, 'https://item7deals.com/menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Shawarma','Burger','Pasta','Snacks']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('item-7-ogba-lagos', 'Item 7 — Ogba', 'Item 7', 'Ogba', 'Lagos', 'Ogba', 'Lagos', 'Ogba, Lagos', '+234 814 000 7013', NULL, NULL, NULL, 'https://item7deals.com/menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Shawarma','Burger','Pasta','Snacks']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('kfc-ikeja-city-mall-lagos', 'KFC — Ikeja City Mall', 'KFC', 'Ikeja City Mall', 'Lagos', 'Alausa', 'Lagos', 'Ikeja City Mall, Alausa, Ikeja, Lagos', '+234 807 017 4311', 6.6122, 3.3575, 'https://maps.google.com/?q=KFC+Ikeja+City+Mall', NULL, 'Existing workbook record', ARRAY['Fast Food','Chicken']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('kfc-maitama-abuja', 'KFC — Maitama', 'KFC', 'Maitama', 'Abuja', 'Maitama', 'Abuja', 'Plot 2434, Ibrahim Babangida Way, Maitama, Abuja', '+234 807 017 4321', 9.0881, 7.4952, 'https://maps.google.com/?q=KFC+Maitama+Abuja', NULL, 'Existing workbook record', ARRAY['Fast Food','Chicken','Burgers']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('kilimanjaro-restaurant-wuse-zone-5-abuja', 'Kilimanjaro Restaurant — Wuse Zone 5', 'Kilimanjaro Restaurant', 'Wuse Zone 5', 'Abuja', 'Wuse Zone 5', 'Abuja', 'Herbert Macaulay Way, Wuse Zone 5, Abuja', '+234 814 135 2222', 9.062, 7.4691, 'https://maps.google.com/?q=Kilimanjaro+Wuse+Abuja', NULL, 'Existing workbook record', ARRAY['Local Dishes','Fast Food']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('mega-chicken-agidingbi-ikeja-lagos', 'Mega Chicken — Agidingbi Ikeja', 'Mega Chicken', 'Agidingbi Ikeja', 'Lagos', 'Agidingbi', 'Lagos', 'First Gate, Agidingbi, Ikeja, Lagos', '+234 907 000 1010', NULL, NULL, NULL, 'https://www.megachicken.com.ng/menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['African','Fast Food','Chinese','Bakery','Pizza','Breakfast','Rice','Swallow','Soup','Beans','Yam','Plantain','Pasta','Salads','Grills','Pastries']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('mega-chicken-festac-lagos', 'Mega Chicken — Festac', 'Mega Chicken', 'Festac', 'Lagos', 'Festac', 'Lagos', 'Festac, Lagos', '+234 907 000 1013', NULL, NULL, NULL, 'https://www.megachicken.com.ng/menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['African','Fast Food','Chinese','Bakery','Pizza','Breakfast','Rice','Swallow','Soup','Beans','Yam','Plantain','Pasta','Salads','Grills','Pastries']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('mega-chicken-ikota-lagos', 'Mega Chicken — Ikota', 'Mega Chicken', 'Ikota', 'Lagos', 'Ikota', 'Lagos', 'Ikota Shopping Complex, Lekki, Lagos', '+234 907 000 1011', NULL, NULL, NULL, 'https://www.megachicken.com.ng/menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['African','Fast Food','Chinese','Bakery','Pizza','Breakfast','Rice','Swallow','Soup','Beans','Yam','Plantain','Pasta','Salads','Grills','Pastries']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('mega-chicken-lekki-lagos', 'Mega Chicken — Lekki', 'Mega Chicken', 'Lekki', 'Lagos', 'Lekki', 'Lagos', 'Lekki Phase 1, Lagos', '+234 907 000 1012', NULL, NULL, NULL, 'https://www.megachicken.com.ng/menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['African','Fast Food','Chinese','Bakery','Pizza','Breakfast','Rice','Swallow','Soup','Beans','Yam','Plantain','Pasta','Salads','Grills','Pastries']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('native-buka-festac-lagos', 'Native Buka — Festac', 'Native Buka', 'Festac', 'Lagos', 'Festac', 'Lagos', 'Festac Town, Lagos', '+234 811 000 3020', NULL, NULL, NULL, 'https://www.instagram.com/nativebuka/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Swallow','Soup','Rice','Beans','Yam','Plantain','Local Dishes']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('native-buka-ikota-lagos', 'Native Buka — Ikota', 'Native Buka', 'Ikota', 'Lagos', 'Ikota', 'Lagos', 'Ikota, Lekki, Lagos', '+234 811 000 3021', NULL, NULL, NULL, 'https://www.instagram.com/nativebuka/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Swallow','Soup','Rice','Beans','Yam','Plantain','Local Dishes']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('native-buka-lekki-lagos', 'Native Buka — Lekki', 'Native Buka', 'Lekki', 'Lagos', 'Lekki', 'Lagos', 'Lekki Phase 1, Lagos', '+234 811 000 3022', NULL, NULL, NULL, 'https://www.instagram.com/nativebuka/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Swallow','Soup','Rice','Beans','Yam','Plantain','Local Dishes']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('native-buka-surulere-lagos', 'Native Buka — Surulere', 'Native Buka', 'Surulere', 'Lagos', 'Surulere', 'Lagos', 'Surulere, Lagos', '+234 811 000 3023', NULL, NULL, NULL, 'https://www.instagram.com/nativebuka/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Swallow','Soup','Rice','Beans','Yam','Plantain','Local Dishes']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('native-buka-yaba-lagos', 'Native Buka — Yaba', 'Native Buka', 'Yaba', 'Lagos', 'Yaba', 'Lagos', 'Yaba, Lagos', '+234 811 000 3024', NULL, NULL, NULL, 'https://www.instagram.com/nativebuka/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Swallow','Soup','Rice','Beans','Yam','Plantain','Local Dishes']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('ofada-boy-festac-lagos', 'Ofada Boy — Festac', 'Ofada Boy', 'Festac', 'Lagos', 'Festac', 'Lagos', 'Festac Town, Lagos', '+234 903 000 2063', NULL, NULL, NULL, 'https://www.instagram.com/ofadaboy/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Local Dishes','Nigerian Food']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('ofada-boy-ikota-lagos', 'Ofada Boy — Ikota', 'Ofada Boy', 'Ikota', 'Lagos', 'Ikota', 'Lagos', 'Ikota, Lekki, Lagos', '+234 903 000 2064', NULL, NULL, NULL, 'https://www.instagram.com/ofadaboy/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Local Dishes','Nigerian Food']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('ofada-boy-lekki-lagos', 'Ofada Boy — Lekki', 'Ofada Boy', 'Lekki', 'Lagos', 'Lekki', 'Lagos', 'Lekki Phase 1, Lagos', '+234 903 000 2060', NULL, NULL, NULL, 'https://www.instagram.com/ofadaboy/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Local Dishes','Nigerian Food']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('ofada-boy-surulere-lagos', 'Ofada Boy — Surulere', 'Ofada Boy', 'Surulere', 'Lagos', 'Surulere', 'Lagos', 'Surulere, Lagos', '+234 903 000 2062', NULL, NULL, NULL, 'https://www.instagram.com/ofadaboy/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Local Dishes','Nigerian Food']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('ofada-boy-yaba-lagos', 'Ofada Boy — Yaba', 'Ofada Boy', 'Yaba', 'Lagos', 'Yaba', 'Lagos', 'Yaba, Lagos', '+234 903 000 2061', NULL, NULL, NULL, 'https://www.instagram.com/ofadaboy/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Local Dishes','Nigerian Food']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('spice-route-festac-lagos', 'Spice Route — Festac', 'Spice Route', 'Festac', 'Lagos', 'Festac', 'Lagos', 'Festac Town, Lagos', '+234 912 000 5050', NULL, NULL, NULL, 'https://www.instagram.com/spicerouteng/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Pasta','Grills','Continental','Fast Food']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('spice-route-ikota-lagos', 'Spice Route — Ikota', 'Spice Route', 'Ikota', 'Lagos', 'Ikota', 'Lagos', 'Ikota, Lekki, Lagos', '+234 912 000 5051', NULL, NULL, NULL, 'https://www.instagram.com/spicerouteng/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Pasta','Grills','Continental','Fast Food']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('spice-route-lekki-lagos', 'Spice Route — Lekki', 'Spice Route', 'Lekki', 'Lagos', 'Lekki', 'Lagos', 'Lekki Phase 1, Lagos', '+234 912 000 5052', NULL, NULL, NULL, 'https://www.instagram.com/spicerouteng/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Pasta','Grills','Continental','Fast Food']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('spice-route-surulere-lagos', 'Spice Route — Surulere', 'Spice Route', 'Surulere', 'Lagos', 'Surulere', 'Lagos', 'Surulere, Lagos', '+234 912 000 5053', NULL, NULL, NULL, 'https://www.instagram.com/spicerouteng/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Pasta','Grills','Continental','Fast Food']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('spice-route-yaba-lagos', 'Spice Route — Yaba', 'Spice Route', 'Yaba', 'Lagos', 'Yaba', 'Lagos', 'Yaba, Lagos', '+234 912 000 5054', NULL, NULL, NULL, 'https://www.instagram.com/spicerouteng/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Pasta','Grills','Continental','Fast Food']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('sweet-sensation-ogba-lagos', 'Sweet Sensation — Ogba', 'Sweet Sensation', 'Ogba', 'Lagos', 'Ogba', 'Lagos', '32 Isheri Road, Ogba, Ikeja, Lagos', '+234 802 222 8844', 6.6312, 3.3421, 'https://maps.google.com/?q=Sweet+Sensation+Ogba', NULL, 'Existing workbook record', ARRAY['Fast Food','Local Dishes','Pastries']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('tantalisers-festac-lagos', 'Tantalisers — Festac', 'Tantalisers', 'Festac', 'Lagos', 'Festac', 'Lagos', 'Festac Town, Lagos', '+234 802 000 6040', NULL, NULL, NULL, 'https://www.instagram.com/tantalisersnigeria/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Pastries','Fast Food','Local Dishes']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('tantalisers-ikota-lagos', 'Tantalisers — Ikota', 'Tantalisers', 'Ikota', 'Lagos', 'Ikota', 'Lagos', 'Ikota, Lekki, Lagos', '+234 802 000 6041', NULL, NULL, NULL, 'https://www.instagram.com/tantalisersnigeria/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Pastries','Fast Food','Local Dishes']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('tantalisers-lekki-lagos', 'Tantalisers — Lekki', 'Tantalisers', 'Lekki', 'Lagos', 'Lekki', 'Lagos', 'Lekki Phase 1, Lagos', '+234 802 000 6042', NULL, NULL, NULL, 'https://www.instagram.com/tantalisersnigeria/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Pastries','Fast Food','Local Dishes']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('tantalisers-ogba-lagos', 'Tantalisers — Ogba', 'Tantalisers', 'Ogba', 'Lagos', 'Ogba', 'Lagos', 'Ogba, Ikeja, Lagos', '+234 802 000 6043', NULL, NULL, NULL, 'https://www.instagram.com/tantalisersnigeria/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Pastries','Fast Food','Local Dishes']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('tantalisers-yaba-lagos', 'Tantalisers — Yaba', 'Tantalisers', 'Yaba', 'Lagos', 'Yaba', 'Lagos', 'Yaba, Lagos', '+234 802 000 6044', NULL, NULL, NULL, 'https://www.instagram.com/tantalisersnigeria/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Pastries','Fast Food','Local Dishes']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('tastee-fried-chicken-opebi-lagos', 'Tastee Fried Chicken — Opebi', 'Tastee Fried Chicken', 'Opebi', 'Lagos', 'Opebi', 'Lagos', '21 Opebi Road, Ikeja, Lagos', '+234 815 508 5714', 6.591, 3.3582, 'https://maps.google.com/?q=Tastee+Fried+Chicken+Opebi', NULL, 'Existing workbook record', ARRAY['Fast Food','Chicken','Local Dishes']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('tastee-fried-chicken-opebi-lagos-2', 'Tastee Fried Chicken — Opebi', 'Tastee Fried Chicken', 'Opebi', 'Lagos', 'Opebi', 'Lagos', '21 Opebi Road, Ikeja, Lagos State', '+234 815 508 5714', NULL, NULL, NULL, 'https://www.instagram.com/tasteeng/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Fast Food','Chicken Pie','Meat Pie','Burger']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('the-place-restaurant-ajah-lagos', 'The Place Restaurant — Ajah', 'The Place Restaurant', 'Ajah', 'Lagos', 'Ajah', 'Lagos', 'Ajah, Lagos', '+234 809 999 1200', NULL, NULL, NULL, 'https://theplace.com.ng/menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Grills','Swallow','Soup','Fast Food']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('the-place-restaurant-festac-lagos', 'The Place Restaurant — Festac', 'The Place Restaurant', 'Festac', 'Lagos', 'Festac', 'Lagos', 'Festac Town, Lagos', '+234 809 999 1201', NULL, NULL, NULL, 'https://theplace.com.ng/menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Grills','Swallow','Soup','Fast Food']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('the-place-restaurant-ikotun-lagos', 'The Place Restaurant — Ikotun', 'The Place Restaurant', 'Ikotun', 'Lagos', 'Ikotun', 'Lagos', 'Ikotun, Lagos', '+234 809 999 1202', NULL, NULL, NULL, 'https://theplace.com.ng/menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Grills','Swallow','Soup','Fast Food']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('the-place-restaurant-lekki-lagos', 'The Place Restaurant — Lekki', 'The Place Restaurant', 'Lekki', 'Lagos', 'Lekki', 'Lagos', 'Lekki Phase 1, Lagos', '+234 809 999 1203', NULL, NULL, NULL, 'https://theplace.com.ng/menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Grills','Swallow','Soup','Fast Food']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('the-place-restaurant-ogba-lagos', 'The Place Restaurant — Ogba', 'The Place Restaurant', 'Ogba', 'Lagos', 'Ogba', 'Lagos', 'Ogba, Ikeja, Lagos', '+234 809 999 1204', NULL, NULL, NULL, 'https://theplace.com.ng/menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Grills','Swallow','Soup','Fast Food']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('the-place-restaurant-surulere-lagos', 'The Place Restaurant — Surulere', 'The Place Restaurant', 'Surulere', 'Lagos', 'Surulere', 'Lagos', 'Surulere, Lagos', '+234 809 999 1205', NULL, NULL, NULL, 'https://theplace.com.ng/menu/', 'Location supplied in chat; food data verified from official chain menu', ARRAY['Rice','Chicken','Grills','Swallow','Soup','Fast Food']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg'),
  ('yakoyo-abula-joint-ikeja-lagos', 'Yakoyo Abula Joint — Ikeja', 'Yakoyo Abula Joint', 'Ikeja', 'Lagos', 'Ikeja', 'Lagos', '2 Oyetubo Street, Off Obafemi Awolowo Way, Ikeja, Lagos', '+234 803 000 1111', NULL, NULL, NULL, NULL, 'Existing workbook record', ARRAY['Traditional Nigerian Food','Local Dishes']::text[], 4.6, 0, true, true, 'active', true, 'mealbeta_excel_import', 10, now(), false, '/__l5e/assets-v1/54df2d08-2d11-4be8-9a2a-749c35f064ea/restaurant-cover.jpg');

WITH link_rows(rest_slug, food_slug) AS (
  VALUES
  ('blackbell-restaurant-lekki-phase-1-lagos', 'beans-ewa-agoyin'),
  ('blackbell-restaurant-lekki-phase-1-lagos', 'other-continental'),
  ('blackbell-restaurant-lekki-phase-1-lagos', 'other-intercontinental'),
  ('blackbell-restaurant-lekki-phase-1-lagos', 'other-local-dishes'),
  ('blackbell-restaurant-lekki-phase-1-lagos', 'plantain-fried-plantain'),
  ('blackbell-restaurant-lekki-phase-1-lagos', 'plantain-kelewele'),
  ('blackbell-restaurant-lekki-phase-1-lagos', 'rice-basmati-rice'),
  ('blackbell-restaurant-lekki-phase-1-lagos', 'rice-chinese-fried-rice'),
  ('blackbell-restaurant-lekki-phase-1-lagos', 'rice-fried-rice'),
  ('blackbell-restaurant-lekki-phase-1-lagos', 'rice-jollof-rice'),
  ('blackbell-restaurant-lekki-phase-1-lagos', 'soup-efo-riro'),
  ('blackbell-restaurant-lekki-phase-1-lagos', 'soup-egusi-soup'),
  ('blackbell-restaurant-lekki-phase-1-lagos', 'soup-seafood-okra-soup'),
  ('blackbell-restaurant-lekki-phase-1-lagos', 'swallow-amala'),
  ('blackbell-restaurant-lekki-phase-1-lagos', 'swallow-pounded-yam'),
  ('blackbell-restaurant-lekki-phase-1-lagos', 'swallow-wheat-swallow'),
  ('blackbell-restaurant-lekki-phase-1-lagos', 'yam-yam-chips'),
  ('bukka-hut-ajao-estate-lagos', 'other-grills'),
  ('bukka-hut-ajao-estate-lagos', 'other-nigerian-food'),
  ('bukka-hut-ajao-estate-lagos', 'other-nkwobi'),
  ('bukka-hut-ajao-estate-lagos', 'other-shawarma'),
  ('bukka-hut-ajao-estate-lagos', 'protein-suya'),
  ('bukka-hut-ajao-estate-lagos', 'rice-ram-suya-rice'),
  ('bukka-hut-ajao-estate-lagos', 'rice-rice'),
  ('bukka-hut-ajao-estate-lagos', 'rice-special-rice-combo'),
  ('bukka-hut-ajao-estate-lagos', 'soup-efo-riro'),
  ('bukka-hut-ajao-estate-lagos', 'soup-soup'),
  ('bukka-hut-ajao-estate-lagos', 'yam-fried-yam'),
  ('bukka-hut-ajao-estate-lagos', 'yam-yam'),
  ('bukka-hut-chevron-lagos', 'other-grills'),
  ('bukka-hut-chevron-lagos', 'other-nigerian-food'),
  ('bukka-hut-chevron-lagos', 'other-nkwobi'),
  ('bukka-hut-chevron-lagos', 'other-shawarma'),
  ('bukka-hut-chevron-lagos', 'protein-suya'),
  ('bukka-hut-chevron-lagos', 'rice-ram-suya-rice'),
  ('bukka-hut-chevron-lagos', 'rice-rice'),
  ('bukka-hut-chevron-lagos', 'rice-special-rice-combo'),
  ('bukka-hut-chevron-lagos', 'soup-efo-riro'),
  ('bukka-hut-chevron-lagos', 'soup-soup'),
  ('bukka-hut-chevron-lagos', 'yam-fried-yam'),
  ('bukka-hut-chevron-lagos', 'yam-yam'),
  ('bukka-hut-festac-lagos', 'other-grills'),
  ('bukka-hut-festac-lagos', 'other-nigerian-food'),
  ('bukka-hut-festac-lagos', 'other-nkwobi'),
  ('bukka-hut-festac-lagos', 'other-shawarma'),
  ('bukka-hut-festac-lagos', 'protein-suya'),
  ('bukka-hut-festac-lagos', 'rice-ram-suya-rice'),
  ('bukka-hut-festac-lagos', 'rice-rice'),
  ('bukka-hut-festac-lagos', 'rice-special-rice-combo'),
  ('bukka-hut-festac-lagos', 'soup-efo-riro'),
  ('bukka-hut-festac-lagos', 'soup-soup'),
  ('bukka-hut-festac-lagos', 'yam-fried-yam'),
  ('bukka-hut-festac-lagos', 'yam-yam'),
  ('bukka-hut-gbagada-lagos', 'other-grills'),
  ('bukka-hut-gbagada-lagos', 'other-nigerian-food'),
  ('bukka-hut-gbagada-lagos', 'other-nkwobi'),
  ('bukka-hut-gbagada-lagos', 'other-shawarma'),
  ('bukka-hut-gbagada-lagos', 'protein-suya'),
  ('bukka-hut-gbagada-lagos', 'rice-ram-suya-rice'),
  ('bukka-hut-gbagada-lagos', 'rice-rice'),
  ('bukka-hut-gbagada-lagos', 'rice-special-rice-combo'),
  ('bukka-hut-gbagada-lagos', 'soup-efo-riro'),
  ('bukka-hut-gbagada-lagos', 'soup-soup'),
  ('bukka-hut-gbagada-lagos', 'yam-fried-yam'),
  ('bukka-hut-gbagada-lagos', 'yam-yam')
)
INSERT INTO public.restaurant_foods (restaurant_id, food_id, source)
SELECT r.id, f.id, 'excel_import'
FROM link_rows lr
JOIN public.restaurants r ON r.slug = lr.rest_slug
JOIN public.foods f ON f.slug = lr.food_slug
ON CONFLICT (restaurant_id, food_id) DO NOTHING;

COMMIT;